imports:
    - php

filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'

tools:
    php_pdepend: false
    php_analyzer: false
    php_sim: false
    # disable copy paste detector and simliarity analyzer as they have no real value
    # and a huge bunch of false-positives
    php_cpd: false
